services:
  # Development Database
  db-dev:
    image: public.ecr.aws/docker/library/mysql:8.0
    container_name: ecommerce-db-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db_dev
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  # Production Database
  db-prod:
    image: public.ecr.aws/docker/library/mysql:8.0
    container_name: ecommerce-db-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db_prod
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

volumes:
  mysql_dev_data:
  mysql_prod_data:
